// Package httpclient provides production-oriented outbound HTTP clients with
// bounded execution, retries, propagation, observability, and optional cached
// dependency health.
//
// # Execution policy
//
// Ordinary requests use DefaultRetryConfig when Config.Retry is zero. Ordinary
// response classification accepts 2xx by default and may be overridden at the
// client or individual request level. Accepted responses are never retried;
// rejected responses remain subject to the configured retry policy. Automatic
// retries also require semantic authorization: standard idempotent methods are
// authorized by default, while POST, PATCH, CONNECT, and custom methods require
// an explicit per-operation assertion. Health checks are disabled by default
// and require both CheckConfig.Enabled and a relative path;
// DefaultCheckConfig is the usual way to enable them. Health checks have
// independent timeout and retry policies. A zero health-check retry policy
// performs one attempt; callers must assign DefaultRetryConfig or another
// complete policy to enable health retries explicitly.
//
// Custom response classifiers must be concurrency-safe, return quickly, and
// must not retain responses or read, close, or replace response bodies.
// Classifier panics and unsupported dispositions become non-retryable policy
// failures without synthesizing Result.Err.
//
// NewRequest resolves references against BaseURL using RFC 3986 semantics.
// BaseURL paths are directory resolution bases rather than confinement
// boundaries: root-relative and parent references may replace or escape them.
// Clientkit still enforces the configured HTTP(S) origin unless cross-origin
// execution is explicitly enabled.
//
// # Observability and readiness
//
// With the owned default net/http client and a nil Observer, Clientkit emits one
// INTERNAL span for the complete logical operation and one CLIENT span for each
// transport RoundTrip, including redirects and retries. Trace context is
// injected from each CLIENT span. Logical and physical spans end when response
// headers or a terminal error are available; they do not depend on callers
// reading or closing response bodies. Clientkit's execution contexts remain
// attached to a returned body until it completes, is closed, or its context is
// done, so callers should still close bodies promptly.
//
// A caller-supplied HTTPClient is never mutated or automatically instrumented.
// Likewise, a non-nil Observer completely replaces automatic observation. Use
// otel.NewTransport on a caller-owned transport when physical OpenTelemetry
// spans are wanted with either of those configurations. This explicit boundary
// avoids duplicate spans when the supplied transport is already instrumented.
// NopObserver and NopHeaderPropagator disable their respective behavior, while
// the Multi variants compose behavior explicitly.
//
// Global OpenTelemetry providers and the global text-map propagator are selected
// when an observer, transport, or Client is constructed, so applications should
// configure them first. Applications own the OpenTelemetry SDK and exporter
// lifecycle. Registry readiness reads cached health and never performs
// synchronous dependency calls.
// HTTP clients report the stable protocol category "http" for both HTTP and
// HTTPS endpoints. Clientkit-controlled telemetry and operational snapshots
// exclude paths, URLs, headers, and bodies. The default OpenTelemetry observer
// also omits raw operation errors; an explicitly configured otel.Observer may
// opt into them with otel.WithErrorDetails. Standard HTTP request-duration
// metrics and request-target span attributes require explicit transport options
// because their server and path dimensions may be sensitive or unsuitable for
// low-cardinality defaults.
//
// # Context metadata
//
// Context-derived request metadata can be injected through HeaderPropagator
// without defining context keys or generating identifiers. Existing headers
// are preserved and values are limited to 256 bytes by default. Invalid values
// and provider panics omit only the affected header and never expose metadata
// through telemetry.
//
// # Configuration examples
//
// The examples below use these module imports:
//
//	import (
//		"context"
//		"net/http"
//		"time"
//
//		clientkit "github.com/jaredjakacky/clientkit"
//		httpclient "github.com/jaredjakacky/clientkit/httpclient"
//		httpclientotel "github.com/jaredjakacky/clientkit/httpclient/otel"
//	)
//
// Application-owned context accessors can supply request and correlation IDs.
// Header names remain configurable and identifiers are not generated by
// Clientkit:
//
//	metadataHeaders, err := httpclient.NewRequestMetadataPropagator(
//		httpclient.RequestMetadataConfig{
//			RequestID: httpclient.HeaderValueProviderFunc(
//				func(ctx context.Context) (string, bool) {
//					return applicationRequestID(ctx)
//				},
//			),
//			RequestIDHeader: "Request-Id",
//			CorrelationID: httpclient.HeaderValueProviderFunc(
//				func(ctx context.Context) (string, bool) {
//					return applicationCorrelationID(ctx)
//				},
//			),
//		},
//	)
//	if err != nil {
//		// handle error
//	}
//
// The metadata propagator can be explicitly composed with OpenTelemetry trace
// propagation:
//
//	metadataClient, err := httpclient.New(httpclient.Config{
//		Config: clientkit.Config{
//			Name: "payments",
//		},
//		BaseURL: "https://payments.internal",
//		Propagator: httpclient.MultiHeaderPropagator(
//			httpclientotel.New(),
//			metadataHeaders,
//		),
//	})
//
// A client-level classifier can accept 404 as a normal catalog result:
//
//	classifier, err := httpclient.AcceptAnyStatus(
//		http.StatusOK,
//		http.StatusNotFound,
//	)
//	if err != nil {
//		// handle error
//	}
//
//	client, err := httpclient.New(httpclient.Config{
//		Config: clientkit.Config{
//			Name: "catalog",
//		},
//		BaseURL:           "https://catalog.internal",
//		ResponseClassifier: classifier,
//	})
//
// An individual request can completely override the client classifier:
//
//	classifier, err := httpclient.AcceptStatus(http.StatusNotModified)
//	if err != nil {
//		// handle error
//	}
//
//	result := client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		ResponseClassifier: classifier,
//	})
//
// Applications can declare a stable, bounded vocabulary for logical operations
// and attach one name to an ordinary execution:
//
//	const (
//		operationCreatePayment httpclient.OperationName = "payments.create"
//		operationLookupPayment httpclient.OperationName = "payments.lookup"
//	)
//
//	result := client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		Operation: operationCreatePayment,
//	})
//
// A caller can explicitly assert that one POST operation is idempotent. Any
// idempotency key remains application-owned:
//
//	request, err := client.NewRequest(
//		context.Background(),
//		http.MethodPost,
//		"/payments",
//		body,
//	)
//	if err != nil {
//		// handle error
//	}
//
//	request.Header.Set("Idempotency-Key", key)
//
//	result := client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		RetrySafety: httpclient.RetrySafetyIdempotent,
//	})
//
// Automatic retries can be disabled for one operation without changing the
// shared client:
//
//	result := client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		Retry: httpclient.ExecutionRetry{
//			Disable: true,
//		},
//	})
//
// A complete custom policy can narrow one operation to two attempts:
//
//	retry := httpclient.DefaultRetryConfig()
//	retry.MaxAttempts = 2
//
//	result := client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		Retry: httpclient.ExecutionRetry{
//			Config: retry,
//		},
//	})
//
// A semantic name composes with custom retry, retry-safety, and timeout policy:
//
//	retry = httpclient.DefaultRetryConfig()
//	retry.MaxAttempts = 2
//	retry.Methods = append(retry.Methods, http.MethodPost)
//
//	result = client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		Operation: operationCreatePayment,
//		Retry: httpclient.ExecutionRetry{
//			Config: retry,
//		},
//		RetrySafety: httpclient.RetrySafetyIdempotent,
//		Timeouts: httpclient.ExecutionTimeouts{
//			Timeout: 2 * time.Second,
//		},
//	})
//
// Total and per-attempt budgets can be shortened independently for one
// operation without mutating the shared client:
//
//	result := client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		Timeouts: httpclient.ExecutionTimeouts{
//			Timeout:        2 * time.Second,
//			AttemptTimeout: 750 * time.Millisecond,
//		},
//	})
//
// A Clientkit total timeout can be disabled while retaining the caller's
// deadline. In this example, the five-minute deadline remains active:
//
//	ctx, cancel := context.WithTimeout(
//		context.Background(),
//		5*time.Minute,
//	)
//	defer cancel()
//
//	request, err := client.NewRequest(
//		ctx,
//		http.MethodGet,
//		"/export",
//		nil,
//	)
//	if err != nil {
//		// handle error
//	}
//
//	result := client.ExecuteWithOptions(request, httpclient.ExecuteOptions{
//		Timeouts: httpclient.ExecutionTimeouts{
//			DisableTimeout: true,
//		},
//	})
//
// A typical enabled check is configured as follows:
//
//	check := httpclient.DefaultCheckConfig("/healthz")
//
//	client, err := httpclient.New(httpclient.Config{
//		Config: clientkit.Config{
//			Name: "payments",
//		},
//		BaseURL: "https://payments.internal",
//		Check:   check,
//	})
//
// A status-class classifier can replace the default exact status:
//
//	check := httpclient.DefaultCheckConfig("/ready")
//	check.ResponseClassifier, err = httpclient.AcceptStatusClass(2)
//	if err != nil {
//		// handle error
//	}
//
// A non-idempotent health-check method also requires explicit authorization in
// addition to inclusion in its complete retry policy:
//
//	check := httpclient.DefaultCheckConfig("/ready")
//	check.Method = http.MethodPost
//	check.Retry = httpclient.DefaultRetryConfig()
//	check.Retry.Methods = append(check.Retry.Methods, http.MethodPost)
//	check.RetrySafety = httpclient.RetrySafetyIdempotent
package httpclient
